Ubuntu_task:
  container:
    image: ubuntu:latest
    cpu: 2
    memory: 128G
  env:
    QEMU_LD_PREFIX: /usr/riscv64-linux-gnu
  setup_script: |
    apt update
    apt install -y meson qemu-user g++-riscv64-linux-gnu gcc-riscv64-linux-gnu
  info_script: |
    meson --version
    ninja --version
  configure_script: meson setup --cross-file cross-config/amd64-riscv64.txt build
  compile_script: meson compile -C build
  test_script: meson test -C build
  #binaries_artifacts:
    #path: "build/**"